[project]
name = 'Multidimensional-Asset-Securitization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cross-dimensional-collateralization]
path = 'contracts/cross-dimensional-collateralization.clar'
clarity_version = 2
epoch = 2.5

[contracts.hyperspatial-property-tokenization]
path = 'contracts/hyperspatial-property-tokenization.clar'
clarity_version = 2
epoch = 2.5

[contracts.n-dimensional-value-assessment]
path = 'contracts/n-dimensional-value-assessment.clar'
clarity_version = 2
epoch = 2.5

[contracts.reality-agnostic-derivative]
path = 'contracts/reality-agnostic-derivative.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
